# Generated by Django 3.1.1 on 2020-10-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='learning_line',
        ),
        migrations.DeleteModel(
            name='LearningLine',
        ),
    ]
