# Generated by Django 3.1.2 on 2020-10-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_graph', '0002_auto_20201011_0828'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='subjects',
        ),
        migrations.AddField(
            model_name='monitor',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='learning_graph.Subject'),
        ),
    ]
