# Generated by Django 3.1.2 on 2020-10-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_graph', '0002_auto_20201011_0828'),
        ('monitor', '0002_auto_20201027_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='subject',
            field=models.ManyToManyField(blank=True, max_length=25, related_name='subjects', to='learning_graph.Subject', verbose_name='subjects'),
        ),
    ]
