# Generated by Django 3.1.2 on 2020-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20201028_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='short_job',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
