# Generated by Django 3.1.2 on 2020-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitor_career_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='career_average',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
