# Generated by Django 3.1.2 on 2020-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20201105_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESELECTION', 'En preselección'), ('DISCARDED', 'No seleccionado'), ('TEST', 'En estado de prueba'), ('SELECTED', 'Permanente')], default='PRESELECTION', max_length=12),
        ),
    ]
