# Generated by Django 3.1.2 on 2020-11-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_monitor_work_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='informatic_tool',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
