# Generated by Django 3.1.2 on 2020-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20201109_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='service_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
