# Generated by Django 3.1.2 on 2020-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20201110_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='informatic_tool',
            field=models.CharField(default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.CharField(blank=True, choices=[('PRESELECTION', 'In preselection'), ('DISCARDED', 'Discarted'), ('TEST', 'In test state'), ('SELECTED', 'Permanent')], default='PRESELECTION', max_length=12),
        ),
    ]
